OBOAcademy/obook

README.md

The link in README.md to https://oboacademy.github.io/obook/getting_started/ didn't quite look right. getting-started (with a dash, not underscore) looks much better. I'm not sure why the underscore partially works though.

#143 fix link to getting-started

---

docs/reference/sparql-reference.md

Adding this example for a few things:
1) Using rdfs:isDefinedBy instead of filtering on string in ubergraph for efficiency  2) Filtering with `or` 
Honestly mainly for me personally cause I keep forgetting point (1)
@nicolevasilevsky sorry for these coming in one by one, I'm adding them as I use them.

add another sparql example

---

docs/explanation/taxon-constraints-explainer.md
docs/howto/add-taxon-restrictions.md

As mentioned in CL call - this is the update for obook taxon documentation. 
@bvarner-ebi will add CL specific stuff in CL docs (eg label conventions) and link to this for more general stuff.

Update Taxon restriction documents

---

docs/courses/monarch-obo-training.md

Removed the Hackathon from the 'Upcoming courses' table and added it to the schedule on November 29, 2022.

Updating OBO Academy schedule

---

docs/lesson/ontology-fundamentals.md

Corrected the spelling of Protégé so it is consistent throughout the whole document. Checked all links to ensure they are working.

correct protege spelling

---

docs/tutorial/odk-toolbox.md
mkdocs.yml

This PR adds a tutorial explaining how to use the various tools that are provided by the ODK, independently of an ODK-managed ontology. That is, it explains how to use `docker run` to invoke a tool from the ODK image to work on local files.

Add a tutorial on how to use the tools from the ODK.

---

docs/courses/monarch-obo-training.md

Jim Balhoff completed the tutorial content update for the 2023-01-10 tutorial on Modeling Taxon Constraints. This update adds the link to the lecture content on the OBO Academy schedule. https://oboacademy.github.io/obook/explanation/taxon-constraints-explainer/

Add Guide to Taxon Restrictions link to schedule

---

docs/courses/monarch-obo-training.md

Updated the schedule to reflect tutorials through March 21, 2023. Added the link to the Introduction to Semantic Entity Matching youtube recording.  https://youtu.be/RN2hYxKYSUw

Update schedule and add recording

---

docs/howto/install-protege.md
mkdocs.yml

1. add new document `install-protege.md`,
2. update [table of contents](https://github.com/OBOAcademy/obook/blob/master/mkdocs.yml)
If applied, this commit will fix #363.

Add new document on how to install Protege

---

docs/courses/monarch-obo-training.md

- Added the *OAK for the Ontology Engineering Community* YouTube video from March 7, 2023 to the schedule.  
- Removed the Upcoming Courses section as it was out of date.  
- Moved the "this is tentative and subject to change" to the Schedule section.

Add OAK tutorial YouTube video

---

docs/courses/monarch-obo-training.md

Update the Monarch OBO Training page to add a link to the supporting slides for the April 2023 “Overview of Protégé 5.6” tutorial.

Add link to the Protégé 5.6 tutorial slides.

---

docs/courses/monarch-obo-training.md

Added the April 2023 OBO Academy training (Introduction to Exomiser and Overview of Protege 5.6) YouTube video links to the schedule table.

Add Exomiser and Protege Youtube video links

---

docs/courses/monarch-obo-training.md

Add title "First steps with ChatGPT for semantic engineers and curators" to schedule for May 30, 2023 tutorial.

Add correct title for May 30, 2023 tutorial

---

docs/courses/monarch-obo-training.md

Updated the schedule table to include a link to the ChatGPT OBOOK pages for the 30 May 2023 tutorial. Also updated the consistency of how presenters are listed in the table. All are now "Tutorial by XYZ" or "Led by XYZ" instead of random.

Updated Schedule Table for 30 May 2023 Tutorial

---

mkdocs.yml

i came here to fix the typo "an GitHub" but while i was at it, i changed a few words in that section of the document to make the bullet points more parallel. note that there are many other places i did not update, but that would benefit from a similar unification of style -- for example, in the section before the one i edited, there are points "Updating Imports" and "Import ORCIDIO". the first of those could be rephrased "Update imports" or the second could be "Importing ORCIDIO".

fixed typo, made some phrasing parallel

---

docs/howto/review-pull-request.md

First, I continue to be amazed at what a great resource the OBOOK is. In this PR, I have suggested a few grammatical fixes and wording improvements and some minor reorganization of some content.
A few things:
1. I'm not sure if I made the correct relative URL here: [here](/howto/github-create-pull-request/)
I tried and failed to find an example of a similar relative reference in an obook module. Please correct as needed.
2. I understand that the point of the "Overarching" section is to summarize the main points of the more detailed "How to" section, but in fact the Overaching section goes into so much detail, it's largely redundant with the How to section. I can't quickly fix that, but I did move the "manual testing" section from the overview down to the more detailed how to section.
3. …

Improvements to documentation about how to review PRs

---

docs/courses/monarch-obo-training.md

Add YouTube recordings for 2023-Sept-19 and 2023-Oct-03 OBO Academy sessions.
The direct links are: 
- 2023-Sept-19 https://youtu.be/_gAdGShZReo?feature=shared
- 2023-Oct-03 https://youtu.be/W4IQk-tft0I?feature=shared
Removed duplicate entry for 2023-Oct-17 OBO Academy session from the schedule.

Add youtube recordings for Sept & Oct 2023

---

docs/tutorial/curies.md

Hello! 
I am not sure how to test if my changes actually helped, but there appeared to be a minor error with the formatting: 
Maybe MkDocs does not like tabs before ```. 
Let me know if anything does not make sense, it is my first PR on this project.

Try to fix formatting issue in curies.md

---

docs/howto/github-create-pull-request.md

I think we need more guidance on what makes a good PR (atomic, don't mix concerns, etc), distinct from the mechanics. I added links to the top for now.
see also:
- https://github.com/INCATools/ontology-development-kit/pull/949
- https://github.com/linkml/linkml-project-cookiecutter/pull/77

Update github-create-pull-request.md, add general guidance on what makes a good PR

---

docs/courses/monarch-obo-training.md

Updated the schedule to cancel the Nov 28, 2023 OBO Academy with Anita Caron on _OBO metadata standardisation_. This will be rescheduled for the early 2024.

Update schedule to cancel Nov 28, 2023

---

docs/tutorial/ontogpt.md

not sure why https://oboacademy.github.io/obook/tutorial/ontogpt/ loses line breaks that look fine in the preview. adding <br/>s that will hopefully help

fix to glommed-together lines?

---

docs/courses/monarch-obo-training.md

Updated the tutorial for April 2, 2024 to be OBO Academy Phenomics Series: Phenotype data and the role of ontologies led by James McLaughlin (EBML-EBI) and Nico Matentzoglu

Update tutorial title & presenters for April 2, 2024

---

docs/courses/monarch-obo-training.md

Adding links to the OBO page or slides for the AI-assisted ontology editing tutorials and the phenotype series tutorial (March and April 2024).

Add links to slides or OBO page for OBO academy schedule

---

docs/howto/setup-docker.md

Added a link to the instructions for [installing Docker on Windows](https://docs.docker.com/desktop/install/windows-install/) to the `setup-docker.md` page.

Add Windows instruction link to setup-docker.md

---

docs/courses/monarch-obo-training.md

Update to the OBO Academy schedule to list the Uberon presentation happening on May 14, 2024.

Update OBO Academy schedule

---

docs/courses/monarch-obo-training.md

Updated the OBO Academy schedule to reflect the schedule for October to December 2024. 
- October 15: Harry lead; Hands on Tutorial part 1: OntoGPT
- November 12: Harry lead; Hands on Tutorial part 2: OntoGPT
- December 10: Eric Rare Disease presentation

Update schedule for Oct to Dec 2024

---

docs/howto/odk-migrate-to-odk.md
docs/tutorial/migrating-ontology-to-odk.md

This PR adds the `odk-migrate-to-odk.md` to the `docs/howto` folder to provide a How To article for the migration of an existing ontology repository to ODK, based on this draft https://docs.google.com/document/d/10i76WqZ8EbnW4ta7BBNqTOYH2tLx51QDzhWF63-80uY/. 
CC:
@matentzn
@cmungall

Add how to migrate to ODK .md and link to it

---

docs/howto/add-taxon-restrictions.md

The previous link for taxon restrictions documentation was broken, I have provided a valid link.

Fix broken link for types of taxon restrictions

---

docs/howto/odk-create-repo.md
docs/tutorial/setting-up-project-odk.md

In the howto and tutorial about setting up a ODK repository, explain that the username and email used for the initial commit may be customised (instead of letting the ODK use the values from the `~/.gitconfig` file, by default) with the `ODK_GITNAME` and `ODK_GITEMAIL` variables.
From [ODK issue 299](https://github.com/INCATools/ontology-development-kit/issues/299), especially [this comment](https://github.com/INCATools/ontology-development-kit/issues/299#issuecomment-2683045229).

Document ODK_GITNAME/ODK_GITEMAIL.
