OBOAcademy/obook

docs/tutorial/managing-ontology-project.md
mkdocs.yml

This is a first stab at building a guide for effective OBO Project Management (not the technical, the managerial part). As much as this is a "lesson", I would like to evolve this into some general guidelines for us all to make ontology management more effective. Its a start at this stage but I will get some feedback.

New Lesson: How to manage an effective Ontology Project

---

docs/lesson/modelling_with_object_properties.md

Small spelling fix
"relation ships" -> "relationships"
---
I have noticed more spelling issues in other entries, but not inclined to go back and look for them at the moment. I think when the next round of OBO trainings comes around (I only got to attend a couple of them this time around), I'll be more proactive about fixing additional spelling errors I find.

Small spelling fix

---

docs/tutorial/fhkb.md

I spotted some issues that seem to be from the Markdown conversion.

Fix issues with Markdown conversion

---

docs/howto/CL-filter.md

Add a document with tips on how to filter large text files.
As discussed with @matentzn .
If applied, this commit will fix #75.

Add tip on how to filter text files

---

docs/lesson/contributing_to_obo_ontologies.md

remove out of date section

---

docs/lesson/contributing_to_obo_ontologies.md

add new example

---

docs/reference/semantic_engineering_toolbox.md
docs/tutorial/sparql.md

See https://github.com/INCATools/ubergraph/pull/38.

Update Ubergraph endpoint to new location

---

docs/howto/odk-create-repo.md

I made a few mistakes and had files in the wrong directories. Hopefully these edits will help someone else avoid my mistakes.

Updated text to include some potential pitfalls

---

docs/index.md

proofreading edits

---

docs/courses/monarch-obo-training.md

last lesson: "creating an ontology from scratch"

added link to recording of the last lesson

---

docs/courses/monarch-obo-training.md

Added SSSOM tutorial link for May 17, 2022 training.

Adding tutorial link for May 17, 2022

---

docs/courses/monarch-obo-training.md

Added the link from google drive to the recording of the SSSOM Tutorial on May 17, 2022.

Add recording from May 17, 2022 Tutorial

---

docs/courses/monarch-obo-training.md

Adding recording from May 31, 2022 tutorial on annotation properties.

Add recording from May 31, 2022

---

docs/courses/monarch-obo-training.md

Add Project Ontology Tutorial recording from June 14, 2022.

Add recording from June 14, 2022

---

docs/howto/github-create-pull-request.md

to address this comment: https://github.com/OBOAcademy/obook/issues/189#issuecomment-1159459863
address #189

add an overview to this how to guide

---

docs/courses/monarch-obo-training.md

Adding OBO Academy recording, Part 1 Basic Introduction to the Command-Line, from June 28, 2022.

Add recording from June 28, 2022

---

docs/howto/installing-elk-in-protege.md

https://oboacademy.github.io/obook/howto/installing-elk-in-protege/

Small detail in https://oboacademy.github.io/obook/howto/installing-elk-in-protege/

---

docs/howto/set-up-protege.md

Create new page set-up-protege.md

---

docs/howto/screenshot.md

Create how to guide on how to create screenshots (partial and full) and paste them into an issue

---

docs/reference/protege-faq.md

One faq: How to escape characters in the class expression editor

add protege-faq.md

---

docs/lesson/analysing-linked-data.md
docs/lesson/automating-ontology-workflows.md
docs/lesson/contributing-to-obo-ontologies.md
docs/lesson/developing-an-obo-ontology.md
docs/lesson/ontology-fundamentals.md
docs/pathways/ontology-contributor.md
docs/reference/formatting-license.md

- Fixing formatting. See #233
- Fixing formatting and fixing typo. See #233
- Fixing formatting. See #233
- Fixing list formatting. See #233. Adding notes on *why* it's important to run the reasoner
- Fixing formatting. #233
- fixing list formatting. See #233

Fixing list formatting in multiple docs, #233

---

docs/howto/merge-terms.md
docs/howto/setup-docker.md

- I added instructions to install docker
- I added a note to refer to the obsoletion how to guide
- I changed mentions of deprecate to obsolete
address #138

add instructions to set up docker/use owltools

---

docs/howto/set-up-protege.md

add instructions on how to increase memory on PC

---

docs/howto/team-open-science-mindset.md

expanded on How to be a team open science player.
This is a rough draft, I will add some more details and flesh out what we have - I just pasted in our notes.
@matentzn for you to do: please write up the intro in the goals section

add text on how to be an open science ontologist

---

docs/howto/github-actions.md
docs/reference/medical-ontology-landscape.md
docs/tutorial/pull-requests.md
mkdocs.yml

close #237 and fix broken links

close #237 and fix broken links

---

.gitignore
README.md

Instructions to run the site locally added to readme.md

Instructions to run the site locally added to readme.md

---

docs/howto/team-open-science-mindset.md

@bvarner-ebi and @megbalk - I pinged you on slack too - I used an example of a ticket/PR that you wrote. Please let me know if it's not okay

add specific examples to How to be an open science ontologist

---

docs/howto/set-up-protege.md

Added alternative path to Info.plist
Added backticks to the "Below the line" and "Insert another line" lines so that the XML tags appear

Mac heap memory size instructions update

---

docs/reference/sparql-reference.md

straightforward example, but didn't see any with multiple triples queried in the example and thought it would be good to have here

Add a sparql example

---

docs/lesson/hackathon.md

I committed my initial changes to master (to create this doc) but remembered you said it is easier to comment on PRs, so I created a PR for some additional edits. Thanks @matentzn!
Feel free to merge this whenever you think it's ready.

create doc for our hackthon on 11/29

---

docs/lesson/contributing-to-obo-ontologies.md

cc @sagehrke + @matentzn 
related to https://github.com/OBOAcademy/obook/pull/294#issuecomment-1324166993

embed video of contributing to ontologies by Sabrina

---

docs/lesson/using-disease-and-phenotype-ontologies.md

Did some minor typo editing for this page.

Fixed typos in the disease-phenotype tutorial

---

docs/lesson/developing-an-obo-ontology.md

Update: Developing an OBO Ontology lesson

---

docs/howto/revert-commit.md

- issue #249 
- added a brief step-by-step guide on how to reverse commits

Created documentation on how to revert a commit using GitHub Desktop

---

docs/lesson/contributing-to-obo-ontologies.md

fix broken links

---

docs/lesson/ontology-pipelines.md

Review Ontology Pipelines with ROBOT lesson

---

docs/404.html
docs/reference/medical-ontology-landscape.md
docs/tutorial/fhkb.md

This PR adds a basic 404 page for mkdocs and updates several links in the docs.

Add 404 page and fix some broken links

---

docs/howto/set-up-protege.md

Especially addressing possible failure points
- #247

Update instructions for configuring Protege memory in MS Windows

---

docs/explanation/taxon-constraints-explainer.md
mkdocs.yml

fixes mermaid graphs are not rendering #333

---

docs/explanation/taxon-constraints-explainer.md

Use 4 spaces for sub-lists

---

mkdocs.yml

Edit button gone in OBOOK?  Fixes #349

Edit button gone in OBOOK?

---

docs/getting-started.md
docs/index.md
docs/lesson/ontology-term-use.md
docs/overview.md

Fix some typos and formatting (take 2)

---

docs/tutorial/monarch-kg-neo4j-basics.md

Embedding the Querying the Monarch KG with Neo4J Youtube video into the OBOOK documentation.

Embed Neo4J OBO Academy Video

---

docs/lesson/entity-matching.md

Embedding Introduction to Semantic Entity Matching youtube video to the OBOOK tutorial page.

Embed video in Semantic Entity Matching Tutorial

---

docs/howto/open-science-engineer.md

Embedding How to be an open science ontologist OBO Academy youtube video to OBOOK documentation. Fixed Table of contents.

Embed How to be an open science ontologist video

---

docs/tutorial/intro-cli-2.md

Embedding Introduction to Command Line Interface Part 2 OBO Academy youtube video.

Embed Intro to CL Part 2 video

---

docs/courses/monarch-obo-training.md

Updated the schedule with the OAK tutorial on March 7th with Chris Mungall

Update schedule with OAK tutorial

---

docs/tutorial/pull-requests.md

Embedding Pull Request Part 1 and 2 OBO Academy youtube videos to OBOOK documentation.

Embed Pull Request tutorial videos

---

docs/courses/monarch-obo-training.md

The tutorial for August 8, 2023 is canceled. Updating the schedule to reflect this change.

Removed tutorial listed for August 8, 2023

---

docs/pathways/ontology-user.md

@sbello could you take a look at this and revise as you see fit? thanks!

create Ontology User pathway

---

docs/pathways/ontology-user.md

It was showing up with everything numbered 1, with no newlines.

Fix list of topics in DO video library

---

docs/courses/monarch-obo-training.md

Add **Modern prefix management with Bioregistry and curies** from 2023/09/05 YouTube recording to schedule:  [link](https://youtu.be/v5hjLgr54Zs?feature=shared)
Add **How to determine if two entities are the same?** from 2023/08/22 YouTube recording to schedule: [link](https://youtu.be/v5hjLgr54Zs?feature=shared)

Add August and September OBO Academy recordings to Schedule 

---

CITATION.cff

This cites a report written by @nicolevasilevsky in the past. Not sure if this is the correct way to do it!

Add CITATION.cff to OBOOK

---

docs/tutorial/units.md
mkdocs.yml

Closes #421
I will probably continue to revise this before and after the tutorial on 2023-10-03.

First draft of units tutorial

---

README.md

Add citation instructions to the README

---

docs/courses/monarch-obo-training.md

Add youtube recording for October 17, 2023 OBO academy **Using ontologies for data annotation and consequences for ontology development** 
Link: https://youtu.be/jRB5VTJLOGc?feature=shared

Add 2023-Oct-17 OBO Academy recording

---

docs/courses/monarch-obo-training.md

Added the CurateGPT YouTube recording form November 17, 2023 OBO Academy. I also cleaned up the Schedule so the formatting is more consistent.

Add 17-Nov-2023 Recording and clean up Schedule

---

docs/tutorial/ontogpt.md

forgot to add link to slides & video, will add in another PR

add content to stub page about OntoGPT

---

docs/courses/monarch-obo-training.md

Add Youtube recording for Introduction to DOSDP tutorial by Ray from December 12, 2023 to OBO Academy OBOOK page.

Add 2023-Dec-12 recording to OBO Academy page

---

docs/courses/monarch-obo-training.md

Updated the schedule to have Harry on January 23rd and Chris M on March 5th.

Updating OBO schedule

---

docs/pathways/ontology-curator-go-style.md

Realised protege link was broken, fixed it

Protege link was broken

---

docs/lesson/contributing-to-obo-ontologies.md

fixes #481
I *think* it just needs the .md - in preview it works so I assume it will when site is built

Fix dead link in contributing-to-obo-ontologies

---

docs/courses/monarch-obo-training.md

Add OBO Academy Youtube recording https://www.youtube.com/watch?v=wGoGr2dmxZI for AI-Assisted Ontology Workflows Part 1

Add OBO Academy recording from 2024-March-05

---

docs/courses/monarch-obo-training.md

Add YouTube link for OBO Academy Phenomics Series tutorial from April 2, 2024: https://youtu.be/9iWRRx7nZlU?feature=shared

Add youtube link for April 2, 2024 OBO Academy

---

docs/courses/monarch-obo-training.md

Add YouTube video links for OBO Academy sessions on April 30, 2024 and April 16, 2024

Add OBO academy recording links

---

docs/courses/monarch-obo-training.md

Add the Introduction to Uberon (Monarch Seminar Series) youtube link to the schedule.

Add Intro to Uberon youtube link

---

docs/courses/monarch-obo-training.md

Updating the schedule to reflect the summer 2024 summer break.

Update monarch-obo-training.md schedule

---

docs/reference/llms.md
mkdocs.yml

Fixes #503 
This is not meant to be the final word, just a first stab at a reference page.

Add a reference page for LLM resources to OBOOK

---

docs/courses/monarch-obo-training.md

Updated the schedule for OBO academy to include fall 2024 dates.

Update schedule for OBO Academy

---

docs/howto/add-coc.md
docs/howto/respectful-collaboration.md
mkdocs.yml

Add COC docs to obook
